apiVersion: v1
kind: Pod
spec:
    containers:
    - name: golang
      image: golang:1.8.0
      command:
        - cat
      tty: true
    - name: python
      image: python:2.7
      command: 
        - cat
      tty: true
    - name: nodejs
      image: node:lts
      command: 
        - cat
      tty: true
    - name: ruby
      image: ruby:2.7.1
      command: 
        - cat
      tty: true
    - name: java
      image: openjdk:11.0.6
      command: 
        - cat
      tty: true